### ISSUE TITLE
Instance of "scoped_session" has no "commit" member

### ISSUE THREAD

**Issue by lkellar** [katzrkool/maps#15]
For some reason, whenever we use the db instance (SQLAlchemy) session, and then some function like commit or instance, pylint freaks out, and it's weird.

This is not an urgent, or even really affecting the product itself, it's just weird, and if anyone knows why, pls share.

**Comment by eblouin876** [comment]
Not sure if this is the error you're getting, but the second answer [here](https://stackoverflow.com/questions/28193025/pylint-cant-find-sqlalchemy-query-member) sounds like it might be useful. Also, this is some impressive code Lucas!

**Comment by lkellar** [comment]
The answer itself didn't end up working, but someone else on that page mentioned putting the `scoped_session` in the `ignored-classes` part of the `.pylintrc`, and that ended up working. Thanks!
